import pandas as pd
from utils.logger import logger

def calculate_momentum(df):
    """
    Calculate team momentum features dynamically using only past game results.
    
    Args:
        df (pd.DataFrame): Game results dataset with "WinFlag" and date columns.
        
    Returns:
        pd.DataFrame: DataFrame with added momentum features.
    """
    try:
        # Ensure data is sorted by season, day number and team id to avoid data leakage.
        df = df.sort_values(by=["Season", "DayNum", "TeamID"])
        # Dummy calculation: momentum is calculated as difference between wins and losses so far.
        df["cumulative_wins"] = df.groupby(["TeamID", "Season"])["WinFlag"].cumsum()
        df["cumulative_games"] = df.groupby(["TeamID", "Season"]).cumcount() + 1
        df["momentum"] = df["cumulative_wins"] - (df["cumulative_games"] - df["cumulative_wins"])
        logger.info("Momentum features calculated successfully.")
    except Exception as e:
        error_message = f"Error calculating momentum: {e}"
        logger.error(error_message)
    return df

# Generated by Nicole LeGuern
